// Generated by CoffeeScript 1.6.2
var add;

add = function(x, y) {
  var oldx, oldy;

  oldx = x;
  oldy = y;
  if (typeof oldy === "undefined") {
    return function(newy) {
      return oldx + newy;
    };
  }
  return x + y;
};

module("currying with add()");

test("it returns a function when called with one one argument", function() {
  return ok(typeof add(5) === "function");
});

test("it returns a number value when called twice", function() {
  return ok(add(3)(4) === 7);
});

test("create and store a new function", function() {
  var add2000;

  add2000 = add(2000);
  return ok(add2000(10) === 2010);
});

/*
//@ sourceMappingURL=currying_test1.map
*/
